language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -f  $HOME/.m2/repository/org/folio/*/*/resolver-status.properties
  - rm -rf $HOME/.m2/repository/org/folio/acquisitions/

